services:
  dev:
    image: 'cuda-dev-env:1.0'
    container_name: cuda-dev
    volumes:
      - ./src:/home/abiel/workspace
    command: tail -f /dev/null
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ['gpu']
              device_ids: ['0']
networks:
  default:
    name: cuda-dev
